name = "HolyLabRegistry"
uuid = "c72e0888-c1c3-11e8-0741-c1bd6f46e678"
repo = "https://github.com/HolyLab/HolyLabRegistry.git"

description = """
Holylab julia package registry where people can
register any package within lab scope.
"""

[packages]
03446670-6174-4c65-a0cf-8126b5696439 = { name = "SupraCubicNumbers", path = "S/SupraCubicNumbers" }
0c2e7f7b-659f-4d17-98b1-b653e143444e = { name = "Autosampler", path = "A/Autosampler" }
0de75c66-c0d4-11e8-3de9-d1632eed9267 = { name = "ISVD", path = "I/ISVD" }
0f17980a-d2b6-11e8-2799-edcc513b22eb = { name = "HistogramPyramids", path = "H/HistogramPyramids" }
13d07ad6-c0d4-11e8-35b1-91a532e61cc8 = { name = "FactoredMatrices", path = "F/FactoredMatrices" }
15f47f3c-50af-56fd-b121-9c5737f4ef3a = { name = "PiezoSerial", path = "P/PiezoSerial" }
189fa2b0-c0d4-11e8-1b41-c5eb7281c27c = { name = "ExtraMatrix", path = "E/ExtraMatrix" }
19baa3cf-15a9-54b0-b671-5d0d7003ae5b = { name = "VariationalOnlineStats", path = "V/VariationalOnlineStats" }
1bab902d-36fe-489f-8fc7-6d2618eb76be = { name = "RoiTool", path = "R/RoiTool" }
22d84090-3402-517d-8c5f-fd8a09276b55 = { name = "ImagineCalibrate", path = "I/ImagineCalibrate" }
23bcbbb2-c0d4-11e8-38f2-37d4ddb111c4 = { name = "TiledFactorizations", path = "T/TiledFactorizations" }
26d16474-33ca-11e9-0261-c59b979c6e18 = { name = "ZWarpedArrays", path = "Z/ZWarpedArrays" }
2857f282-5c94-11e9-0b5d-cb5f26255b42 = { name = "ImageInterpLast", path = "I/ImageInterpLast" }
28fce3f0-1dbc-11e9-10e3-e71e6ceb4e7c = { name = "Imagine", path = "I/Imagine" }
2b713a72-c0d4-11e8-0e3e-e7c72182117a = { name = "MergePairwise", path = "M/MergePairwise" }
304b7e5e-c0d4-11e8-1391-db3dfdb9ef20 = { name = "CellSegmentation", path = "C/CellSegmentation" }
30e56b64-2659-11e9-2fbf-0524297743d8 = { name = "RegisterWorkerAperturesMismatch", path = "R/RegisterWorkerAperturesMismatch" }
35e57d1e-36d7-11e9-1ca9-f74434b2bc55 = { name = "InterleavedImages", path = "I/InterleavedImages" }
36121b08-3789-5198-aff2-59a3443d9b59 = { name = "RegisterFit", path = "R/RegisterFit" }
387662ca-47fb-11e9-36d5-97ab6f05d7f8 = { name = "ExtractPSF", path = "E/ExtractPSF" }
395f9d9a-971b-4d1d-8fea-4857c99358f6 = { name = "TaylorRemainders", path = "T/TaylorRemainders" }
3bd9afcd-55df-531a-9b34-dc642dce7b95 = { name = "RFFT", path = "R/RFFT" }
3c0dd727-6833-5f5d-a1e8-c0d421935c74 = { name = "RegisterMismatch", path = "R/RegisterMismatch" }
43b7f2cc-1a9d-11e9-093e-178b9f97357d = { name = "ImagineProcedures", path = "I/ImagineProcedures" }
45426be3-ce3a-4f7b-a429-3e2aa7698a5f = { name = "PhaseOptimizedComponentAnalysis", path = "P/PhaseOptimizedComponentAnalysis" }
464fa2a9-b19c-5c59-8698-f58c971f971e = { name = "RegisterPenalty", path = "R/RegisterPenalty" }
46a7138f-0d70-54e1-8ada-fb8296f91f24 = { name = "CenterIndexedArrays", path = "C/CenterIndexedArrays" }
55325cc8-c0ec-11e8-2109-1f9bd277abf4 = { name = "ShotNoise", path = "S/ShotNoise" }
56f27cf3-5d2e-53a9-a1df-46b7fbe4d4d0 = { name = "DFoFArrays", path = "D/DFoFArrays" }
597c7b4e-c0ec-11e8-1347-855d2b7c9c20 = { name = "FakeCells", path = "F/FakeCells" }
5d60e731-3d07-5a0e-bd67-2fa232a8a749 = { name = "BlockRegistrationScheduler", path = "B/BlockRegistrationScheduler" }
629045b3-4d2b-4a55-9b3a-009cda0386a9 = { name = "StimulusNavigator", path = "S/StimulusNavigator" }
67712758-55e7-5c3c-8e85-dda1d7758434 = { name = "RegisterCore", path = "R/RegisterCore" }
6a7ac665-a291-440c-97b5-1e881457f238 = { name = "StitchDPI", path = "S/StitchDPI" }
73fda715-febb-5522-a0fc-086e91958f61 = { name = "RegisterHindsight", path = "R/RegisterHindsight" }
75ec5d3c-0ed3-11e9-24c7-e530058603ef = { name = "ImagineHardware", path = "I/ImagineHardware" }
768c9593-c1e5-5107-8576-9ed3f4373482 = { name = "CoordinateSplittingPTrees", path = "C/CoordinateSplittingPTrees" }
7ecfceec-b993-11e8-0809-a584061f8d98 = { name = "OptimizeIVQ", path = "O/OptimizeIVQ" }
935ac36e-2656-11e9-1e3b-cbaa636797af = { name = "RegisterDriver", path = "R/RegisterDriver" }
96ae54c0-0dff-11e9-11b2-27e67f6cc5ea = { name = "UnitAliases", path = "U/UnitAliases" }
96be3cfc-dfc9-41f0-9424-fd41ed36fd5e = { name = "BlockRegistration", path = "B/BlockRegistration" }
97563a55-ea3b-5e9e-8052-20bacb65643b = { name = "LightsheetDestripe", path = "L/LightsheetDestripe" }
978d31ce-2656-11e9-22d6-b5c46a1a3d3e = { name = "RegisterWorkerShell", path = "R/RegisterWorkerShell" }
99b0285a-20f0-11e9-0283-7f418f478feb = { name = "FastScanning", path = "F/FastScanning" }
9cc36475-e10c-57f8-b33d-19dcb253ebc3 = { name = "BoxTrees", path = "B/BoxTrees" }
9da5b20e-4a71-11e9-15f0-a14dcb3a4cc0 = { name = "MergeUnreciprocated", path = "M/MergeUnreciprocated" }
a0a6461a-57d1-11e9-363b-71a271cc5699 = { name = "RegisterWorkerApertures", path = "R/RegisterWorkerApertures" }
a9d8408c-0fb1-11e9-0067-cb067474114e = { name = "ImagineInterface", path = "I/ImagineInterface" }
abb2e897-52bf-5d28-a379-6ca321e3b878 = { name = "RegisterMismatchCommon", path = "R/RegisterMismatchCommon" }
ac24ea0c-1830-11e9-18d4-81f172323054 = { name = "RegisterQD", path = "R/RegisterQD" }
b89da37c-15e8-11e9-0b03-ab0995a60613 = { name = "CachedCalls", path = "C/CachedCalls" }
b9709bfb-d23d-5560-8276-8c35c4b76823 = { name = "CachedInterpolations", path = "C/CachedInterpolations" }
b981a1b5-4587-53b0-9c3d-454c648f6f8d = { name = "RegisterOptimize", path = "R/RegisterOptimize" }
bc20c4a6-ae8f-539c-9805-f1e868603a0f = { name = "LinearKernelModels", path = "L/LinearKernelModels" }
c09c51bc-9ae7-4408-96c2-ae54f7cea0d3 = { name = "SymmetricComponentAnalysis", path = "S/SymmetricComponentAnalysis" }
c19381b7-cf49-59d7-881c-50dfbd227eaf = { name = "RegisterDeformation", path = "R/RegisterDeformation" }
c3b4e2a2-e463-46f1-b1f5-667b5e187791 = { name = "MappedIndexArrays", path = "M/MappedIndexArrays" }
cd6f60fb-236b-5882-ad4f-250d5433a9a7 = { name = "TileTrees", path = "T/TileTrees" }
d076106b-79cb-5c5e-aa42-567a067496c5 = { name = "ImaginePlots", path = "I/ImaginePlots" }
d32f3a2f-26fa-5ce0-a2ac-000c59351c13 = { name = "NeighborhoodClustering", path = "N/NeighborhoodClustering" }
d4862ba2-f42c-5aeb-af4f-96a8884a16c4 = { name = "RegisterUtilities", path = "R/RegisterUtilities" }
d514a27a-15fd-11e9-2877-55d10791f35b = { name = "ImagineAnalyses", path = "I/ImagineAnalyses" }
d8fd01e4-1764-11e9-0a01-8f76bebf08d8 = { name = "CachedArrays", path = "C/CachedArrays" }
dae52e8d-d666-5120-a592-9e15c33b8d7a = { name = "QuadDIRECT", path = "Q/QuadDIRECT" }
e6cd4d91-e4e0-4df6-b8b9-468a61cefdb4 = { name = "MergeUnreciprocatedGUI", path = "M/MergeUnreciprocatedGUI" }
ee0d8d85-fa18-576c-9601-66ebb12862d9 = { name = "RegisterMismatchCuda", path = "R/RegisterMismatchCuda" }
f385d984-c960-11e8-171c-977bba6b62a4 = { name = "IntervalFastMath", path = "I/IntervalFastMath" }
f54becb8-3809-5a58-8f2d-748913078968 = { name = "TileTreesGUI", path = "T/TileTreesGUI" }
fda17f23-89d5-4117-bd1e-27859bb918b7 = { name = "LCSVD", path = "L/LCSVD" }
ff578f10-1de7-11e9-075b-65d52eaf0ec5 = { name = "ImagineWorker", path = "I/ImagineWorker" }
